version: "3.4"

services:
  db:
    container_name: banco_postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: my_db
    ports:
      - "15432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql"
      - "./scripts:/docker-entrypoint-initdb.d"

volumes:
    postgres_data:
        external: false